### PR TITLE
document the axeslbl function

### PR DESCRIPTION
**Pull request by v0dro**
Discussion in #79 documented in code.

### CODE REVIEW

**Comment by FlorianRhiem** [comment]
Thanks! Could you add a simple, possibly single-line description to the start, basically the Doxygen "brief"?

**Comment by v0dro** [comment]
Sure.

**Comment by v0dro** [comment]
Done.

**Comment by FlorianRhiem** [comment]
Merged, the conflict GitHub reports is just due to two code style fixes between your original commit and the merged one. Thank you!

**Pull request closed without merging**
